import type { Metadata } from "next";
import { Syne, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { baseMetaKeywords } from '../seo/meta-keywords';
import { myInfoSchema } from '../seo/schema';
import { GoogleTagManager } from '@next/third-parties/google'
import dynamic from  'next/dynamic'
import { Analytics } from "@vercel/analytics/next"

const Navbar = dynamic(() => import('./_components/navbar'))
const Footer = dynamic(() => import('./_components/footer'))
const syne = Syne({
  subsets: ["latin"],
  weight: ["700", "800"],
  variable: "--font-syne",
  display: "swap",
});

// 2. Configura a JetBrains Mono para os textos, códigos e detalhes
const mono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-mono",
  display: "swap",
});

const baseUrl = process?.env.PROJECT_URL || ""

export const metadata: Metadata = {
  metadataBase: new URL(baseUrl),
  icons:{
    icon:'/favicon.ico'
  },
  title: {
    default:"Victor Kiss | Software Engineer",
    template:"%s | Victor Kiss"
  },
  description: "Generated by create next app",
  keywords: baseMetaKeywords,
  authors: [{ name: 'Victor Kiss' }],
  openGraph: {
    type: 'website',
    locale: 'pt_BR',
    url: baseUrl,
    title: 'Victor Kiss | Software Engineer',
    description: 'Portfólio de engenharia de software.',
    siteName: 'Victor Kiss',
  },
  alternates: {
    canonical: './'
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  const gtag = process.env.GTAG_ID || ""
  return (
    <html
      suppressHydrationWarning
      lang="pt-br"
      className={`${syne.variable} ${mono.variable} h-full antialiased`}
    >
      <head>
           <script async={true}
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(myInfoSchema) }}
      />
      </head>
       <GoogleTagManager gtmId={gtag} />
   
      <body className="min-h-full flex flex-col">
        <header>
          <Navbar/>
        </header>
       <main>{children}</main>
        <Analytics/>
        <Footer/>
      </body>

       
    </html>
  );
}
